# Generated by Django 3.1.6 on 2021-02-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('teams', models.ManyToManyField(to='app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('indicator_type', models.CharField(max_length=100)),
                ('indicator_value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('teams', models.ManyToManyField(to='app.Team')),
            ],
        ),
    ]
